# Publish the Jupyter Book from source files

name: publish-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make cache folder
      run: mkdir ~/cache
    - name: Cache Dockerfile
      id: cache-docker
      uses: actions/cache@v3
      with:
        path: ~/cache/Dockerfile
        key: Dockerfile-${{ hashFiles('docker/Dockerfile') }}
    - name: touch ~/cache/Dockerfile
      run: touch ~/cache/Dockerfile
    - name: compare Dockerfile with cache
      id: diff
      run: |
          if diff docker/Dockerfile ~/cache/Dockerfile > /dev/null; then
              echo ::set-output name=changed::no
          else
              echo ::set-output name=changed::yes
          fi

    - name: set Docker tag
      run: |
        if ${{ steps.diff.outputs.changed }}="yes"; then
            echo ::set-output name=tag::"${GITHUB_HEAD_REF#refs/heads/}"
        else
            echo ::set-output name=tag::latest
        fi
      id: dockertag
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      # if: steps.diff.outputs.changed == 'yes'
    - name: Copy Dockerfile to ~/cache/Dockerfile
      run: cp docker/Dockerfile ~/cache/Dockerfile
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      # if: steps.diff.outputs.changed == 'yes'
    - name: Build Docker images
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: caknowledgebase/caknowledgebase:${{ steps.dockertag.outputs.tag }}
        target: ca-knowledgebase
        file: docker/Dockerfile
      # if: github.ref == 'refs/heads/main'
      # if: ${{ github.ref == 'refs/heads/main' && steps.diff.outputs.changed == 'yes' }}
      # if: steps.diff.outputs.changed == 'yes'

  deploy-book:
    runs-on: ubuntu-latest
    container: caknowledgebase/caknowledgebase:${{ needs.build-docker.steps.dockertag.outputs.tag }}
    needs:
    - build-docker
    
    steps:
    - uses: actions/checkout@v2

    - run: echo ${{ needs.build-docker.steps.dockertag.outputs.tag }}

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    # Build the book
    - name: Build the book
      run: |
        PYVISTA_JUPYTER_BACKEND=static PYVISTA_OFF_SCREEN=false jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        cname: knowledgebase.acoustics.ac.uk
      if: github.ref == 'refs/heads/main'
